# Set to true, if you want to fully override the default configuration.
override: false
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# To get or check favicons visit: https://realfavicongenerator.net
favicon:
  small: /uploads/favicon-16x16.png
  medium: /uploads/favicon-32x32.png
  apple_touch_icon: /uploads/favicon-32x32.png
  safari_pinned_tab: /uploads/favicon-32x32.png
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml

# Set default keywords (Use a comma to separate)
keywords: "人工智障,深度瞎调"
# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss: /atom.xml
footer:
  since: 2018
  icon: heart
# SEO Settings
# Canonical, set a canonical link tag in your hexo, you could use it for your SEO of blog.
canonical: true
# Change headers hierarchy on site-subtitle (will be main site description) and on all post/pages titles for better SEO-optimization.
seo: true
# If true, will add site-subtitle to index page, added in main hexo config.
subtitle: Subtitle
index_with_subtitle: true
# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
# Usage: `Key: /link/ || icon`
menu:
  home: / || home
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  about: /about/ || user
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
menu_icons:
  enable: true
scheme: Mist
# Sidebar Settings
social:
  GitHub: https://github.com/hjptriplebee || github
  #E-Mail: mailto:huangjipengnju@gmail.com || envelope
  CSDN: http://blog.csdn.net/accepthjp || crosshairs
  Weibo: https://weibo.com/u/5271192594 || weibo
social_icons:
  enable: true
  icons_only: false
  transition: false
# Blog rolls
links_icon: link
links_title: 友情链接
links_layout: inline
links:
  推理与学习研究组: https://cs.nju.edu.cn/rl/
  小题大做-Leetcode: http://blog.csdn.net/column/details/12689.html
  计算机视觉与深度学习: http://blog.csdn.net/column/details/12802.html
  老博客: http://blog.csdn.net/accepthjp
  tensorflow: https://www.tensorflow.org/

# Sidebar Avatar
avatar: /uploads/author.jpg
# Table Of Contents in the Sidebar
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false

sidebar:
  # Sidebar Position, available value: left | right (only for Pisces | Gemini).
  position: left
  #position: right
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  display: always
  #display: always
  #display: hide
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12
  # Back to top in sidebar (only for Pisces | Gemini).
  b2t: false
  # Scroll percent label in b2t button.
  scrollpercent: true
  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: false
# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------
# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true
# Automatically saving scroll position on each post/page in cookies.
save_scroll: false
# Automatically excerpt description in homepage as preamble text.
excerpt_description: true
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 200

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true
# Post wordcount display settings
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true
  totalcount: true
  separated_meta: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

# Reward
reward_comment: 本文已结束，谢谢阅读！
wechatpay: /uploads/weixin.jpg
alipay: /uploads/zhifubao.jpg
# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------
# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: false
# Android Chrome header panel color ($black-deep).
android_chrome_color: "#222"
# Code Highlight theme: normal | night | night eighties | night blue | night bright
highlight_theme: night
# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------
# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
han: true

# Gitment
gitment:
  enable: true
  mint: true # RECOMMEND, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: true # Hide 'Powered by ...' on footer, and more
  language: zh-Hans # Force language, or auto switch by theme
  github_user: hjptriplebee # MUST HAVE, Your Github ID
  github_repo: gitment # MUST HAVE, The repo you use to store Gitment comments
  client_id: 4e66fa2a9b6189967d5d # MUST HAVE, Github client id for the Gitment
  client_secret: 912b738018be59734db3d650643a5006ade2cece # EITHER this or proxy_gateway, Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled

# NeedMoreShare2
# iconStyle: default | box
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
needmoreshare2:
  enable: true
  float:
    enable: true
    options:
      iconStyle: default
      boxForm: horizontal
      position: middleLeft
      networks: Weibo,Wechat,Douban,QQZone,GooglePlus

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:

# Google Analytics
google_analytics: UA-113518079-1

# ---------------------------------------------------------------
busuanzi_count:
  enable: true
  site_uv: true
  site_uv_header: <i class="fa fa-user"> 访客数</i>
  site_uv_footer: 
  site_pv: true
  site_pv_header: <i class="fa fa-eye"> 访问量</i>
  site_pv_footer: 
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"> 阅读量</i>
  page_pv_footer: 
# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: true
# Local search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: -1

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------
# External URL with BASE64 encrypt & decrypt.
# Usage: {% exturl text url "title" %}
# Alias: {% extlink text url "title" %}
exturl: false

# Note tag (bs-callout).
note:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# Label tag.
label: true

# Tabs tag.
tabs:
  enable: true
  transition:
    tabs: false
    labels: true
  border_radius: 0
#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------
# Use velocity to animate everything.
motion:
  enable: true
  async: false
  transition:
    post_block: fadeIn
    post_header: slideDownIn
    post_body: slideDownIn
    coll_header: slideLeftIn
    sidebar: slideUpIn
# Fancybox
fancybox: true
# Progress bar in the top during page loading.
pace: true
pace_theme: pace-theme-flash
canvas_nest: false
three_waves: false
canvas_lines: false
canvas_sphere: false
# Script Vendors.
# For example:jquery: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
# Be aware that you should use the same version as internal ones to avoid potential problems.
# Please use the https protocol of CDN files when you enable https on your site.
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: lib
  jquery:
  # See: http://fancyapps.com/fancybox/
  fancybox:
  fancybox_css:
  # See: https://github.com/ftlabs/fastclick
  fastclick:
  # See: https://github.com/tuupola/jquery_lazyload
  lazyload:
  # See: http://VelocityJS.org
  velocity:
  # See: http://VelocityJS.org
  velocity_ui:
  # See: https://faisalman.github.io/ua-parser-js/
  ua_parser:
  # See: http://fontawesome.io/
  fontawesome:
  # https://www.algolia.com
  algolia_instant_js:
  algolia_instant_css:
  # See: https://github.com/HubSpot/pace
  pace:
  pace_css:
  canvas_nest:
  three:
  three_waves:
  canvas_lines:
  canvas_sphere:
  canvas_ribbon:
  han:
  needMoreShare2:

# Assets
css: css
js: js
images: images
# Theme version
version: 5.1.4
